// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChCjlBPWbJde8hoRM20YzcxTatAEZO3q4',
    appId: '1:205365666721:web:7635da85a6be4b312ce1e0',
    messagingSenderId: '205365666721',
    projectId: 'myapp-d7dfc',
    authDomain: 'myapp-d7dfc.firebaseapp.com',
    storageBucket: 'myapp-d7dfc.firebasestorage.app',
    measurementId: 'G-Q9ZXPJ3FG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0oN-EsuYyOpoMndYAyCyEywu4JhepIaI',
    appId: '1:205365666721:android:2851bc0abeb90d602ce1e0',
    messagingSenderId: '205365666721',
    projectId: 'myapp-d7dfc',
    storageBucket: 'myapp-d7dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzPdqqMCOMJNfmTm0x8C80GjBv64cVXc',
    appId: '1:205365666721:ios:dd791e2a1e8906662ce1e0',
    messagingSenderId: '205365666721',
    projectId: 'myapp-d7dfc',
    storageBucket: 'myapp-d7dfc.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
